---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: angular-app-deployment
spec:
 replicas: 2
 selector:
   matchLabels:
     app: app
 template:
  metadata:
   name: app
   labels:
     app: app
  spec:
    containers:
    - name: angular-app-container
      image: mukeshrakh10/ng-app-image
      ports:
      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
 name: angular-app-svc
spec:
  type: NodePort
  selector:
   app: app
  ports:
   - port: 80
     targetPort: 80
     nodePort: 30002
...

